name: Highlight Risky Zones in PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest

    steps:

    - name: Run Risk Analysis
      uses: savinmikhail/pr_risky_zones_highlighter@v1.1.0
      with:
        gpt_api_key: ${{ secrets.GPT_API_KEY }}
        gpt_url: 'https://api.proxyapi.ru/openai'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo_full_name: ${{ github.repository }}
        pull_number: ${{ github.event.pull_request.number }}
