name: Highlight Risky Zones in PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run custom action
      uses: savinmikhail/pr_risky_zones_highlighter@v0.1.0
      with:
        gpt_api_key: ${{ secrets.GPT_API_KEY }}
